# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln'
  netfxsolution: 'WPFSamples.sln'
  netcoresolution: 'WPFSamples.netcore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Download and Cache Nuget tool'

- task: NuGetCommand@2
  displayName: 'Restore Solutions'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build .NET Framework Samples'
  inputs:
    vsVersion: latest
    solution: '$(netfxsolution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: /m /bl:$(Build.ArtifactStagingDirectory)\netfx.binlog
  continueOnError: true

- task: VSBuild@1
  displayName: 'Build .NET Core Samples'
  inputs:
    vsVersion: latest
    solution: '$(netcoresolution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: /m /bl:$(Build.ArtifactStagingDirectory)\netcore.binlog
  continueOnError: true

- task: PublishBuildArtifacts@1
  name: PublishLogs
  displayName: 'Publish Build Logs'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\*.binlog
    ArtifactName: msbuild.binlog
    publishLocation: 'Container'