cd "%~dp0\Accessibility\FetchTimer\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\FetchTimer\bin\Debug\net5.0-windows\win-arm64\publish\FetchTimer.exe"
cd "%~dp0\Accessibility\FindText\FindText\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\FindText\FindText\bin\Debug\net5.0-windows\win-arm64\publish\FindText.exe"
cd "%~dp0\Accessibility\FocusTracker\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\FocusTracker\bin\Debug\net5.0-windows\win-arm64\publish\FocusTracker.exe"
cd "%~dp0\Accessibility\InsertText\InsertTextTarget\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\InsertText\InsertTextTarget\bin\Debug\net5.0-windows\win-arm64\publish\InsertTextTarget.exe"
cd "%~dp0\Accessibility\InvokePattern\Target\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\InvokePattern\Target\bin\Debug\net5.0-windows\win-arm64\publish\Target.exe"
cd "%~dp0\Accessibility\SelectionPattern\SelectionTarget\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\SelectionPattern\SelectionTarget\bin\Debug\net5.0-windows\win-arm64\publish\SelectionTarget.exe"
cd "%~dp0\Accessibility\WindowMove\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Accessibility\WindowMove\bin\Debug\net5.0-windows\win-arm64\publish\WindowMove.exe"
cd "%~dp0\Animation\AnimationExamples\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\AnimationExamples\bin\Debug\net5.0-windows\win-arm64\publish\AnimationExamples.exe"
cd "%~dp0\Animation\AnimationTiming\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\AnimationTiming\bin\Debug\net5.0-windows\win-arm64\publish\AnimationTiming.exe"
cd "%~dp0\Animation\CustomAnimation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\CustomAnimation\bin\Debug\net5.0-windows\win-arm64\publish\CustomAnimation.exe"
cd "%~dp0\Animation\KeyFrameAnimation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\KeyFrameAnimation\bin\Debug\net5.0-windows\win-arm64\publish\KeyFrameAnimation.exe"
cd "%~dp0\Animation\KeySplineAnimations\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\KeySplineAnimations\bin\Debug\net5.0-windows\win-arm64\publish\KeySplineAnimations.exe"
cd "%~dp0\Animation\LocalAnimations\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\LocalAnimations\bin\Debug\net5.0-windows\win-arm64\publish\LocalAnimations.exe"
cd "%~dp0\Animation\OpacityAnimation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\OpacityAnimation\bin\Debug\net5.0-windows\win-arm64\publish\OpacityAnimation.exe"
cd "%~dp0\Animation\PathAnimations\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\PathAnimations\bin\Debug\net5.0-windows\win-arm64\publish\PathAnimations.exe"
cd "%~dp0\Animation\Per-FrameAnimation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\Per-FrameAnimation\bin\Debug\net5.0-windows\win-arm64\publish\Per-FrameAnimation.exe"
cd "%~dp0\Animation\PropertyAnimation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\PropertyAnimation\bin\Debug\net5.0-windows\win-arm64\publish\PropertyAnimation.exe"
cd "%~dp0\Animation\TargetValues\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Animation\TargetValues\bin\Debug\net5.0-windows\win-arm64\publish\TargetValues.exe"
cd "%~dp0\Application Management\ApplicationShutdown\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\ApplicationShutdown\bin\Debug\net5.0-windows\win-arm64\publish\ApplicationShutdown.exe"
cd "%~dp0\Application Management\CodeOnlyWindowsApplication\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\CodeOnlyWindowsApplication\bin\Debug\net5.0-windows\win-arm64\publish\CodeOnlyWindowsApplication.exe"
cd "%~dp0\Application Management\CustomApplication\CustomApplicationClass\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\CustomApplication\CustomApplicationClass\bin\Debug\net5.0-windows\win-arm64\publish\CustomApplicationClass.exe"
cd "%~dp0\Application Management\ExceptionHandlingSecondaryUIThread\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\ExceptionHandlingSecondaryUIThread\bin\Debug\net5.0-windows\win-arm64\publish\ExceptionHandlingSecondaryUIThread.exe"
cd "%~dp0\Application Management\ExceptionHandlingSecondaryWorkerThread\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\ExceptionHandlingSecondaryWorkerThread\bin\Debug\net5.0-windows\win-arm64\publish\ExceptionHandlingSecondaryWorkerThread.exe"
cd "%~dp0\Application Management\ProcessingCommandLineArguments\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\ProcessingCommandLineArguments\bin\Debug\net5.0-windows\win-arm64\publish\ProcessingCommandLineArguments.exe"
cd "%~dp0\Application Management\SkinnedApplication\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\SkinnedApplication\bin\Debug\net5.0-windows\win-arm64\publish\SkinnedApplication.exe"
cd "%~dp0\Application Management\UnhandledExceptionHandling\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Application Management\UnhandledExceptionHandling\bin\Debug\net5.0-windows\win-arm64\publish\UnhandledExceptionHandling.exe"
cd "%~dp0\Clipboard\ClipboardSpy\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Clipboard\ClipboardSpy\bin\Debug\net5.0-windows\win-arm64\publish\ClipboardSpy.exe"
cd "%~dp0\Clipboard\ClipboardViewer\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Clipboard\ClipboardViewer\bin\Debug\net5.0-windows\win-arm64\publish\ClipboardViewer.exe"
cd "%~dp0\Compatibility\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Compatibility\bin\Debug\net5.0-windows\win-arm64\publish\AppCompat-Quirks.exe"
cd "%~dp0\Data Binding\BindConversion\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\BindConversion\bin\Debug\net5.0-windows\win-arm64\publish\BindConversion.exe"
cd "%~dp0\Data Binding\BindingDPToDP\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\BindingDPToDP\bin\Debug\net5.0-windows\win-arm64\publish\BindingDPToDP.exe"
cd "%~dp0\Data Binding\BindingToMethod\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\BindingToMethod\bin\Debug\net5.0-windows\win-arm64\publish\BindingToMethod.exe"
cd "%~dp0\Data Binding\BindValidation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\BindValidation\bin\Debug\net5.0-windows\win-arm64\publish\BindValidation.exe"
cd "%~dp0\Data Binding\BusinessLayerValidation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\BusinessLayerValidation\bin\Debug\net5.0-windows\win-arm64\publish\BusinessLayerValidation.exe"
cd "%~dp0\Data Binding\CodeOnlyBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\CodeOnlyBinding\bin\Debug\net5.0-windows\win-arm64\publish\CodeOnlyBinding.exe"
cd "%~dp0\Data Binding\CollectionBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\CollectionBinding\bin\Debug\net5.0-windows\win-arm64\publish\CollectionBinding.exe"
cd "%~dp0\Data Binding\CollectionViewSource\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\CollectionViewSource\bin\Debug\net5.0-windows\win-arm64\publish\CollectionViewSource.exe"
cd "%~dp0\Data Binding\Colors\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\Colors\bin\Debug\net5.0-windows\win-arm64\publish\Colors.exe"
cd "%~dp0\Data Binding\CompositeCollections\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\CompositeCollections\bin\Debug\net5.0-windows\win-arm64\publish\CompositeCollections.exe"
cd "%~dp0\Data Binding\DataBindingToStringFomat\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\DataBindingToStringFomat\bin\Debug\net5.0-windows\win-arm64\publish\DataBindingToStringFomat.exe"
cd "%~dp0\Data Binding\DataTemplatingIntro\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\DataTemplatingIntro\bin\Debug\net5.0-windows\win-arm64\publish\DataTemplatingIntro.exe"
cd "%~dp0\Data Binding\DataTrigger\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\DataTrigger\bin\Debug\net5.0-windows\win-arm64\publish\DataTrigger.exe"
cd "%~dp0\Data Binding\DirectionalBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\DirectionalBinding\bin\Debug\net5.0-windows\win-arm64\publish\DirectionalBinding.exe"
cd "%~dp0\Data Binding\EditingCollections\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\EditingCollections\bin\Debug\net5.0-windows\win-arm64\publish\EditingCollections.exe"
cd "%~dp0\Data Binding\Grouping\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\Grouping\bin\Debug\net5.0-windows\win-arm64\publish\Grouping.exe"
cd "%~dp0\Data Binding\HierarchicalDataTemplate\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\HierarchicalDataTemplate\bin\Debug\net5.0-windows\win-arm64\publish\HierarchicalDataTemplate.exe"
cd "%~dp0\Data Binding\Linq\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\Linq\bin\Debug\net5.0-windows\win-arm64\publish\Linq.exe"
cd "%~dp0\Data Binding\MasterDetail\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\MasterDetail\bin\Debug\net5.0-windows\win-arm64\publish\MasterDetail.exe"
cd "%~dp0\Data Binding\MasterDetailXml\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\MasterDetailXml\bin\Debug\net5.0-windows\win-arm64\publish\MasterDetailXml.exe"
cd "%~dp0\Data Binding\MultiBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\MultiBinding\bin\Debug\net5.0-windows\win-arm64\publish\MultiBinding.exe"
cd "%~dp0\Data Binding\PriorityBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\PriorityBinding\bin\Debug\net5.0-windows\win-arm64\publish\PriorityBinding.exe"
cd "%~dp0\Data Binding\PropertyChangeNotification\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\PropertyChangeNotification\bin\Debug\net5.0-windows\win-arm64\publish\PropertyChangeNotification.exe"
cd "%~dp0\Data Binding\SimpleBinding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\SimpleBinding\bin\Debug\net5.0-windows\win-arm64\publish\SimpleBinding.exe"
cd "%~dp0\Data Binding\SortFilter\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\SortFilter\bin\Debug\net5.0-windows\win-arm64\publish\SortFilter.exe"
cd "%~dp0\Data Binding\UpdateSource\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\UpdateSource\bin\Debug\net5.0-windows\win-arm64\publish\UpdateSource.exe"
cd "%~dp0\Data Binding\ValidateItemSample\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\ValidateItemSample\bin\Debug\net5.0-windows\win-arm64\publish\ValidateItemSample.exe"
cd "%~dp0\Data Binding\ValidateItemsInItemsControl\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\ValidateItemsInItemsControl\bin\Debug\net5.0-windows\win-arm64\publish\ValidateItemsInItemsControl.exe"
cd "%~dp0\Data Binding\XmlDataSource\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\XmlDataSource\bin\Debug\net5.0-windows\win-arm64\publish\XmlDataSource.exe"
cd "%~dp0\Data Binding\XmlnsBind\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Data Binding\XmlnsBind\bin\Debug\net5.0-windows\win-arm64\publish\XmlnsBind.exe"
cd "%~dp0\Documents\Annotations\AnnotatedDocumentViewer\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Annotations\AnnotatedDocumentViewer\bin\Debug\net5.0-windows\win-arm64\publish\AnnotatedDocumentViewer.exe"
cd "%~dp0\Documents\Annotations\AnnotationsStyling\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Annotations\AnnotationsStyling\bin\Debug\net5.0-windows\win-arm64\publish\AnnotationsStyling.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentMerge\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Fixed Documents\DocumentMerge\bin\Debug\net5.0-windows\win-arm64\publish\DocumentMerge.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentSerialization\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Fixed Documents\DocumentSerialization\bin\Debug\net5.0-windows\win-arm64\publish\DocumentSerialization.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentStructure\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Fixed Documents\DocumentStructure\bin\Debug\net5.0-windows\win-arm64\publish\DocumentStructure.exe"
cd "%~dp0\Documents\Flow Content\FlowContentElements\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\FlowContentElements\bin\Debug\net5.0-windows\win-arm64\publish\FlowContentElements.exe"
cd "%~dp0\Documents\Flow Content\FlowContentProperty\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\FlowContentProperty\bin\Debug\net5.0-windows\win-arm64\publish\FlowContentProperty.exe"
cd "%~dp0\Documents\Flow Content\FlowDocumentNewsClient\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\FlowDocumentNewsClient\bin\Debug\net5.0-windows\win-arm64\publish\FlowDocumentNewsClient.exe"
cd "%~dp0\Documents\Flow Content\FlowDocumentProperties\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\FlowDocumentProperties\bin\Debug\net5.0-windows\win-arm64\publish\FlowDocumentProperties.exe"
cd "%~dp0\Documents\Flow Content\FontProperties\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\FontProperties\bin\Debug\net5.0-windows\win-arm64\publish\FontProperties.exe"
cd "%~dp0\Documents\Flow Content\ParagraphAndHyphenation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\ParagraphAndHyphenation\bin\Debug\net5.0-windows\win-arm64\publish\ParagraphAndHyphenation.exe"
cd "%~dp0\Documents\Flow Content\TableBuilder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\TableBuilder\bin\Debug\net5.0-windows\win-arm64\publish\TableBuilder.exe"
cd "%~dp0\Documents\Flow Content\TableRows\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\TableRows\bin\Debug\net5.0-windows\win-arm64\publish\TableRows.exe"
cd "%~dp0\Documents\Flow Content\TabularData\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\TabularData\bin\Debug\net5.0-windows\win-arm64\publish\TabularData.exe"
cd "%~dp0\Documents\Flow Content\TextWrapProperty\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Flow Content\TextWrapProperty\bin\Debug\net5.0-windows\win-arm64\publish\TextWrapProperty.exe"
cd "%~dp0\Documents\Spell Checking\CustomDictionaries\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Spell Checking\CustomDictionaries\bin\Debug\net5.0-windows\win-arm64\publish\CustomDictionaries.exe"
cd "%~dp0\Documents\Spell Checking\SpellChecking\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Documents\Spell Checking\SpellChecking\bin\Debug\net5.0-windows\win-arm64\publish\SpellChecking.exe"
cd "%~dp0\Drag and Drop\DragDropDataFormats\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropDataFormats\bin\Debug\net5.0-windows\win-arm64\publish\DragDropDataFormats.exe"
cd "%~dp0\Drag and Drop\DragDropEvents\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropEvents\bin\Debug\net5.0-windows\win-arm64\publish\DragDropEvents.exe"
cd "%~dp0\Drag and Drop\DragDropObjects\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropObjects\bin\Debug\net5.0-windows\win-arm64\publish\DragDropObjects.exe"
cd "%~dp0\Drag and Drop\DragDropOpenTextFile\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropOpenTextFile\bin\Debug\net5.0-windows\win-arm64\publish\DragDropOpenTextFile.exe"
cd "%~dp0\Drag and Drop\DragDropTextOps\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropTextOps\bin\Debug\net5.0-windows\win-arm64\publish\DragDropTextOps.exe"
cd "%~dp0\Drag and Drop\DragDropThumbOps\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Drag and Drop\DragDropThumbOps\bin\Debug\net5.0-windows\win-arm64\publish\DragDropThumbOps.exe"
cd "%~dp0\Element Tree\OverridingLogicalTree\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Element Tree\OverridingLogicalTree\bin\Debug\net5.0-windows\win-arm64\publish\OverridingLogicalTree.exe"
cd "%~dp0\Element Tree\SearchingForElement\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Element Tree\SearchingForElement\bin\Debug\net5.0-windows\win-arm64\publish\SearchingForElement.exe"
cd "%~dp0\Elements\ContextMenuOpening\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\ContextMenuOpening\bin\Debug\net5.0-windows\win-arm64\publish\ContextMenuOpening.exe"
cd "%~dp0\Elements\FindingElementInPanel\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\FindingElementInPanel\bin\Debug\net5.0-windows\win-arm64\publish\FindingElementInPanel.exe"
cd "%~dp0\Elements\FocusVisualStyle\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\FocusVisualStyle\bin\Debug\net5.0-windows\win-arm64\publish\FocusVisualStyle.exe"
cd "%~dp0\Elements\HeightProperties\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\HeightProperties\bin\Debug\net5.0-windows\win-arm64\publish\HeightProperties.exe"
cd "%~dp0\Elements\LoadedEvent\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\LoadedEvent\bin\Debug\net5.0-windows\win-arm64\publish\LoadedEvent.exe"
cd "%~dp0\Elements\SettingMargins\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\SettingMargins\bin\Debug\net5.0-windows\win-arm64\publish\SettingMargins.exe"
cd "%~dp0\Elements\ThicknessConverter\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\ThicknessConverter\bin\Debug\net5.0-windows\win-arm64\publish\ThicknessConverter.exe"
cd "%~dp0\Elements\UsingElements\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\UsingElements\bin\Debug\net5.0-windows\win-arm64\publish\UsingElements.exe"
cd "%~dp0\Elements\VisibiltyChanges\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\VisibiltyChanges\bin\Debug\net5.0-windows\win-arm64\publish\VisibiltyChanges.exe"
cd "%~dp0\Elements\WidthProperties\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Elements\WidthProperties\bin\Debug\net5.0-windows\win-arm64\publish\WidthProperties.exe"
cd "%~dp0\Events\AddingEventHandler\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Events\AddingEventHandler\bin\Debug\net5.0-windows\win-arm64\publish\AddingEventHandler.exe"
cd "%~dp0\Events\CustomRoutedEvents\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Events\CustomRoutedEvents\bin\Debug\net5.0-windows\win-arm64\publish\CustomRoutedEvents.exe"
cd "%~dp0\Events\FindingSourceElement\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Events\FindingSourceElement\bin\Debug\net5.0-windows\win-arm64\publish\FindingSourceElement.exe"
cd "%~dp0\Events\RoutedEventHandling\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Events\RoutedEventHandling\bin\Debug\net5.0-windows\win-arm64\publish\RoutedEventHandling.exe"
cd "%~dp0\Getting Started\ComplexLayout\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\ComplexLayout\bin\Debug\net5.0-windows\win-arm64\publish\ComplexLayout.exe"
cd "%~dp0\Getting Started\Concepts\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\Concepts\bin\Debug\net5.0-windows\win-arm64\publish\Concepts.exe"
cd "%~dp0\Getting Started\ControlsAndLayout\ControlsAndLayout\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\ControlsAndLayout\ControlsAndLayout\bin\Debug\net5.0-windows\win-arm64\publish\ControlsAndLayout.exe"
cd "%~dp0\Getting Started\DynamicLayout\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\DynamicLayout\bin\Debug\net5.0-windows\win-arm64\publish\DynamicLayout.exe"
cd "%~dp0\Getting Started\HelloWorld\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\HelloWorld\bin\Debug\net5.0-windows\win-arm64\publish\HelloWorld.exe"
cd "%~dp0\Getting Started\MultiPage\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\MultiPage\bin\Debug\net5.0-windows\win-arm64\publish\MultiPage.exe"
cd "%~dp0\Getting Started\SimpleLayout\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\SimpleLayout\bin\Debug\net5.0-windows\win-arm64\publish\SimpleLayout.exe"
cd "%~dp0\Getting Started\WalkthroughFirstWPFApp\csharp\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Getting Started\WalkthroughFirstWPFApp\csharp\bin\Debug\net5.0-windows\win-arm64\publish\ExpenseIt9.exe"
cd "%~dp0\Globalization and Localization\BAML Loc\LocApp\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\BAML Loc\LocApp\bin\Debug\net5.0-windows\win-arm64\publish\LocApp.exe"
cd "%~dp0\Globalization and Localization\FlowDirection\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\FlowDirection\bin\Debug\net5.0-windows\win-arm64\publish\FlowDirection.exe"
cd "%~dp0\Globalization and Localization\GlobalizationHomepage\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\GlobalizationHomepage\bin\Debug\net5.0-windows\win-arm64\publish\GlobalizationHomepage.exe"
cd "%~dp0\Globalization and Localization\GlobalizationRunDialog\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\GlobalizationRunDialog\bin\Debug\net5.0-windows\win-arm64\publish\GlobalizationRunDialog.exe"
cd "%~dp0\Globalization and Localization\Gradient\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\Gradient\bin\Debug\net5.0-windows\win-arm64\publish\Gradient.exe"
cd "%~dp0\Globalization and Localization\Image\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\Image\bin\Debug\net5.0-windows\win-arm64\publish\Image.exe"
cd "%~dp0\Globalization and Localization\LangAttribute\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\LangAttribute\bin\Debug\net5.0-windows\win-arm64\publish\LangAttribute.exe"
cd "%~dp0\Globalization and Localization\LocalizationResources\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\LocalizationResources\bin\Debug\net5.0-windows\win-arm64\publish\LocalizationResources.exe"
cd "%~dp0\Globalization and Localization\LTRRTL\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\LTRRTL\bin\Debug\net5.0-windows\win-arm64\publish\LTRRTL.exe"
cd "%~dp0\Globalization and Localization\NumbersMultipleLangauges\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\NumbersMultipleLangauges\bin\Debug\net5.0-windows\win-arm64\publish\NumbersMultipleLangauges.exe"
cd "%~dp0\Globalization and Localization\Paths\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\Paths\bin\Debug\net5.0-windows\win-arm64\publish\Paths.exe"
cd "%~dp0\Globalization and Localization\RunSpan\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\RunSpan\bin\Debug\net5.0-windows\win-arm64\publish\RunSpan.exe"
cd "%~dp0\Globalization and Localization\Span\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\Span\bin\Debug\net5.0-windows\win-arm64\publish\Span.exe"
cd "%~dp0\Globalization and Localization\StringLocalizationSample\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Globalization and Localization\StringLocalizationSample\bin\Debug\net5.0-windows\win-arm64\publish\StringLocalizationSample.exe"
cd "%~dp0\Graphics\2DTransforms\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\2DTransforms\bin\Debug\net5.0-windows\win-arm64\publish\2DTransforms.exe"
cd "%~dp0\Graphics\BitmapEffectsGallery\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\BitmapEffectsGallery\bin\Debug\net5.0-windows\win-arm64\publish\BitmapEffectsGallery.exe"
cd "%~dp0\Graphics\BitmapMetadata\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\BitmapMetadata\bin\Debug\net5.0-windows\win-arm64\publish\BitmapMetadata.exe"
cd "%~dp0\Graphics\BMPEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\BMPEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\BMPEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Brushes\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Brushes\bin\Debug\net5.0-windows\win-arm64\publish\Brushes.exe"
cd "%~dp0\Graphics\ClipRegion\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\ClipRegion\bin\Debug\net5.0-windows\win-arm64\publish\ClipRegion.exe"
cd "%~dp0\Graphics\Converter\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Converter\bin\Debug\net5.0-windows\win-arm64\publish\Converter.exe"
cd "%~dp0\Graphics\DrawingBrush\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\DrawingBrush\bin\Debug\net5.0-windows\win-arm64\publish\DrawingBrush.exe"
cd "%~dp0\Graphics\Geometry\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Geometry\bin\Debug\net5.0-windows\win-arm64\publish\Geometry.exe"
cd "%~dp0\Graphics\GIFEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\GIFEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\GIFEncoderAndDecoder.exe"
cd "%~dp0\Graphics\ImageBrush\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\ImageBrush\bin\Debug\net5.0-windows\win-arm64\publish\ImageBrush.exe"
cd "%~dp0\Graphics\ImageView\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\ImageView\bin\Debug\net5.0-windows\win-arm64\publish\ImageView.exe"
cd "%~dp0\Graphics\JPEGEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\JPEGEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\JPEGEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Matrix\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Matrix\bin\Debug\net5.0-windows\win-arm64\publish\Matrix.exe"
cd "%~dp0\Graphics\OpacityMasking\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\OpacityMasking\bin\Debug\net5.0-windows\win-arm64\publish\OpacityMasking.exe"
cd "%~dp0\Graphics\PNGEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\PNGEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\PNGEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Point\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Point\bin\Debug\net5.0-windows\win-arm64\publish\Point.exe"
cd "%~dp0\Graphics\ShapeElements\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\ShapeElements\bin\Debug\net5.0-windows\win-arm64\publish\ShapeElements.exe"
cd "%~dp0\Graphics\ShapesGallery\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\ShapesGallery\bin\Debug\net5.0-windows\win-arm64\publish\ShapesGallery.exe"
cd "%~dp0\Graphics\SystemBrushesAndColors\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\SystemBrushesAndColors\bin\Debug\net5.0-windows\win-arm64\publish\SystemBrushesAndColors.exe"
cd "%~dp0\Graphics\TIFFEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\TIFFEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\TIFFEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Vector\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\Vector\bin\Debug\net5.0-windows\win-arm64\publish\Vector.exe"
cd "%~dp0\Graphics\VisualBrush\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\VisualBrush\bin\Debug\net5.0-windows\win-arm64\publish\VisualBrush.exe"
cd "%~dp0\Graphics\WDPEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Graphics\WDPEncoderAndDecoder\bin\Debug\net5.0-windows\win-arm64\publish\WDPEncoderAndDecoder.exe"
cd "%~dp0\Input and Commands\CaptureUnCaptureMouse\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Input and Commands\CaptureUnCaptureMouse\bin\Debug\net5.0-windows\win-arm64\publish\CaptureUnCaptureMouse.exe"
cd "%~dp0\Input and Commands\CommandSourceControlUsingSystemTimer\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Input and Commands\CommandSourceControlUsingSystemTimer\bin\Debug\net5.0-windows\win-arm64\publish\CommandSourceControlUsingSystemTimer.exe"
cd "%~dp0\Input and Commands\CommandSourceControlWithDispatcherTimer\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Input and Commands\CommandSourceControlWithDispatcherTimer\bin\Debug\net5.0-windows\win-arm64\publish\CommandSourceControlWithDispatcherTimer.exe"
cd "%~dp0\Input and Commands\CursorType\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Input and Commands\CursorType\bin\Debug\net5.0-windows\win-arm64\publish\CursorType.exe"
cd "%~dp0\Input and Commands\ProgrammaticFocusControl\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Input and Commands\ProgrammaticFocusControl\bin\Debug\net5.0-windows\win-arm64\publish\ProgrammaticFocusControl.exe"
cd "%~dp0\PerMonitorDPI\FormattedTextExample\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\PerMonitorDPI\FormattedTextExample\bin\Debug\net5.0-windows\win-arm64\publish\FormattedTextExample.exe"
cd "%~dp0\PerMonitorDPI\ImageScaling\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\PerMonitorDPI\ImageScaling\bin\Debug\net5.0-windows\win-arm64\publish\ImageScaling.exe"
cd "%~dp0\PerMonitorDPI\TextFormatting\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\PerMonitorDPI\TextFormatting\bin\Debug\net5.0-windows\win-arm64\publish\TextFormatting.exe"
cd "%~dp0\Properties\Callbacks\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Properties\Callbacks\bin\Debug\net5.0-windows\win-arm64\publish\Callbacks.exe"
cd "%~dp0\Properties\CustomClassesWithDP\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Properties\CustomClassesWithDP\bin\Debug\net5.0-windows\win-arm64\publish\CustomClassesWithDP.exe"
cd "%~dp0\Properties\RestoringDefaultValues\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Properties\RestoringDefaultValues\bin\Debug\net5.0-windows\win-arm64\publish\RestoringDefaultValues.exe"
cd "%~dp0\Resources\ApplicationResources\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Resources\ApplicationResources\bin\Debug\net5.0-windows\win-arm64\publish\ApplicationResources.exe"
cd "%~dp0\Resources\DefiningResources\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Resources\DefiningResources\bin\Debug\net5.0-windows\win-arm64\publish\DefiningResources.exe"
cd "%~dp0\Resources\MergedResources\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Resources\MergedResources\bin\Debug\net5.0-windows\win-arm64\publish\MergedResources.exe"
cd "%~dp0\Sample Applications\CalculatorDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\CalculatorDemo\bin\Debug\net5.0-windows\win-arm64\publish\CalculatorDemo.exe"
cd "%~dp0\Sample Applications\ConcentricRingsDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\ConcentricRingsDemo\bin\Debug\net5.0-windows\win-arm64\publish\ConcentricRingsDemo.exe"
cd "%~dp0\Sample Applications\CubeAnimationDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\CubeAnimationDemo\bin\Debug\net5.0-windows\win-arm64\publish\CubeAnimationDemo.exe"
cd "%~dp0\Sample Applications\CustomComboBox\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\CustomComboBox\bin\Debug\net5.0-windows\win-arm64\publish\CustomComboBox.exe"
cd "%~dp0\Sample Applications\DataBindingDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\DataBindingDemo\bin\Debug\net5.0-windows\win-arm64\publish\DataBindingDemo.exe"
cd "%~dp0\Sample Applications\DropShadow\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\DropShadow\bin\Debug\net5.0-windows\win-arm64\publish\DropShadow.exe"
cd "%~dp0\Sample Applications\EditingExaminerDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\EditingExaminerDemo\bin\Debug\net5.0-windows\win-arm64\publish\EditingExaminerDemo.exe"
cd "%~dp0\Sample Applications\ExpenseIt\ExpenseItDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\ExpenseIt\ExpenseItDemo\bin\Debug\net5.0-windows\win-arm64\publish\ExpenseIt9.exe"
cd "%~dp0\Sample Applications\FontDialog\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\FontDialog\bin\Debug\net5.0-windows\win-arm64\publish\FontDialog.exe"
cd "%~dp0\Sample Applications\GeometryDesignerDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\GeometryDesignerDemo\bin\Debug\net5.0-windows\win-arm64\publish\GeometryDesignerDemo.exe"
cd "%~dp0\Sample Applications\GraphingCalculatorDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\GraphingCalculatorDemo\bin\Debug\net5.0-windows\win-arm64\publish\GraphingCalculatorDemo.exe"
cd "%~dp0\Sample Applications\HexSphereDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\HexSphereDemo\bin\Debug\net5.0-windows\win-arm64\publish\HexSphereDemo.exe"
cd "%~dp0\Sample Applications\HtmlToXamlDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\HtmlToXamlDemo\bin\Debug\net5.0-windows\win-arm64\publish\HtmlToXamlDemo.exe"
cd "%~dp0\Sample Applications\LayoutTransitionsDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\LayoutTransitionsDemo\bin\Debug\net5.0-windows\win-arm64\publish\LayoutTransitionsDemo.exe"
cd "%~dp0\Sample Applications\ParticlesDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\ParticlesDemo\bin\Debug\net5.0-windows\win-arm64\publish\ParticlesDemo.exe"
cd "%~dp0\Sample Applications\PhotoFlipperDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\PhotoFlipperDemo\bin\Debug\net5.0-windows\win-arm64\publish\PhotoFlipperDemo.exe"
cd "%~dp0\Sample Applications\PhotoStoreDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\PhotoStoreDemo\bin\Debug\net5.0-windows\win-arm64\publish\PhotoStoreDemo.exe"
cd "%~dp0\Sample Applications\PhotoViewerDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\PhotoViewerDemo\bin\Debug\net5.0-windows\win-arm64\publish\PhotoViewerDemo.exe"
cd "%~dp0\Sample Applications\SlidePuzzleDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\SlidePuzzleDemo\bin\Debug\net5.0-windows\win-arm64\publish\SlidePuzzleDemo.exe"
cd "%~dp0\Sample Applications\StickyNotesDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\StickyNotesDemo\bin\Debug\net5.0-windows\win-arm64\publish\StickyNotesDemo.exe"
cd "%~dp0\Sample Applications\VideoViewerDemo\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Sample Applications\VideoViewerDemo\bin\Debug\net5.0-windows\win-arm64\publish\VideoViewerDemo.exe"
cd "%~dp0\Speech and Media\MediaGallery\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Speech and Media\MediaGallery\bin\Debug\net5.0-windows\win-arm64\publish\MediaGallery.exe"
cd "%~dp0\Styles & Templates\AlternatingAppearanceOfItems\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Styles & Templates\AlternatingAppearanceOfItems\bin\Debug\net5.0-windows\win-arm64\publish\AlternatingAppearanceOfItems.exe"
cd "%~dp0\Styles & Templates\ContentControlStyle\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Styles & Templates\ContentControlStyle\bin\Debug\net5.0-windows\win-arm64\publish\ContentControlStyle.exe"
cd "%~dp0\Styles & Templates\EventTriggers\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Styles & Templates\EventTriggers\bin\Debug\net5.0-windows\win-arm64\publish\EventTriggers.exe"
cd "%~dp0\Styles & Templates\FindingElementsInTemplates\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Styles & Templates\FindingElementsInTemplates\bin\Debug\net5.0-windows\win-arm64\publish\FindingElementsInTemplates.exe"
cd "%~dp0\Styles & Templates\IntroToStylingAndTemplating\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Styles & Templates\IntroToStylingAndTemplating\bin\Debug\net5.0-windows\win-arm64\publish\IntroToStylingAndTemplating.exe"
cd "%~dp0\Threading\MultiThreadingWebBrowser\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Threading\MultiThreadingWebBrowser\bin\Debug\net5.0-windows\win-arm64\publish\MultiThreadingWebBrowser.exe"
cd "%~dp0\Threading\SingleThreadedApplication\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Threading\SingleThreadedApplication\bin\Debug\net5.0-windows\win-arm64\publish\SingleThreadedApplication.exe"
cd "%~dp0\Threading\UsingDispatcher\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Threading\UsingDispatcher\bin\Debug\net5.0-windows\win-arm64\publish\UsingDispatcher.exe"
cd "%~dp0\Visual Layer\CompositionTarget\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Visual Layer\CompositionTarget\bin\Debug\net5.0-windows\win-arm64\publish\CompositionTarget.exe"
cd "%~dp0\Visual Layer\DrawingVisual\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Visual Layer\DrawingVisual\bin\Debug\net5.0-windows\win-arm64\publish\DrawingVisual.exe"
cd "%~dp0\Visual Layer\VisualsHitTesting\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Visual Layer\VisualsHitTesting\bin\Debug\net5.0-windows\win-arm64\publish\VisualsHitTesting.exe"
cd "%~dp0\Windows\CustomWindowUI\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\CustomWindowUI\bin\Debug\net5.0-windows\win-arm64\publish\CustomWindowUI.exe"
cd "%~dp0\Windows\DialogBox\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\DialogBox\bin\Debug\net5.0-windows\win-arm64\publish\DialogBox.exe"
cd "%~dp0\Windows\MessageBox\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\MessageBox\bin\Debug\net5.0-windows\win-arm64\publish\MessageBox.exe"
cd "%~dp0\Windows\NonRectangularWindow\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\NonRectangularWindow\bin\Debug\net5.0-windows\win-arm64\publish\NonRectangularWindow.exe"
cd "%~dp0\Windows\NotificationIcon\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\NotificationIcon\bin\Debug\net5.0-windows\win-arm64\publish\NotificationIcon.exe"
cd "%~dp0\Windows\SaveWindowState\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\SaveWindowState\bin\Debug\net5.0-windows\win-arm64\publish\SaveWindowState.exe"
cd "%~dp0\Windows\ShowWindowWithoutActivation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\ShowWindowWithoutActivation\bin\Debug\net5.0-windows\win-arm64\publish\ShowWindowWithoutActivation.exe"
cd "%~dp0\Windows\WindowActivationAndDeactivation\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\WindowActivationAndDeactivation\bin\Debug\net5.0-windows\win-arm64\publish\WindowActivationAndDeactivation.exe"
cd "%~dp0\Windows\WindowHiding\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\WindowHiding\bin\Debug\net5.0-windows\win-arm64\publish\WindowHiding.exe"
cd "%~dp0\Windows\WindowSizingOrder\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\WindowSizingOrder\bin\Debug\net5.0-windows\win-arm64\publish\WindowSizingOrder.exe"
cd "%~dp0\Windows\Wizard\bin\Debug\net5.0-windows\win-arm64\publish\"
"%~dp0\Windows\Wizard\bin\Debug\net5.0-windows\win-arm64\publish\Wizard.exe"
