REM runsamples_block3.bat <runtime identifier>
REM ex: runsamples_block3 win-x64
REM ex: runsamples_block3 win-arm64
REM ex: runsamples_block3 win-x86
cd "%~dp0\Graphics\OpacityMasking\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\OpacityMasking\bin\Debug\net5.0-windows\%1\publish\OpacityMasking.exe"
cd "%~dp0\Graphics\PNGEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\PNGEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\PNGEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Point\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Point\bin\Debug\net5.0-windows\%1\publish\Point.exe"
cd "%~dp0\Graphics\ShapeElements\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\ShapeElements\bin\Debug\net5.0-windows\%1\publish\ShapeElements.exe"
cd "%~dp0\Graphics\ShapesGallery\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\ShapesGallery\bin\Debug\net5.0-windows\%1\publish\ShapesGallery.exe"
cd "%~dp0\Graphics\SystemBrushesAndColors\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\SystemBrushesAndColors\bin\Debug\net5.0-windows\%1\publish\SystemBrushesAndColors.exe"
cd "%~dp0\Graphics\TIFFEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\TIFFEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\TIFFEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Vector\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Vector\bin\Debug\net5.0-windows\%1\publish\Vector.exe"
cd "%~dp0\Graphics\VisualBrush\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\VisualBrush\bin\Debug\net5.0-windows\%1\publish\VisualBrush.exe"
cd "%~dp0\Graphics\WDPEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\WDPEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\WDPEncoderAndDecoder.exe"
cd "%~dp0\Input and Commands\CaptureUnCaptureMouse\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Input and Commands\CaptureUnCaptureMouse\bin\Debug\net5.0-windows\%1\publish\CaptureUnCaptureMouse.exe"
cd "%~dp0\Input and Commands\CommandSourceControlUsingSystemTimer\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Input and Commands\CommandSourceControlUsingSystemTimer\bin\Debug\net5.0-windows\%1\publish\CommandSourceControlUsingSystemTimer.exe"
cd "%~dp0\Input and Commands\CommandSourceControlWithDispatcherTimer\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Input and Commands\CommandSourceControlWithDispatcherTimer\bin\Debug\net5.0-windows\%1\publish\CommandSourceControlWithDispatcherTimer.exe"
cd "%~dp0\Input and Commands\CursorType\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Input and Commands\CursorType\bin\Debug\net5.0-windows\%1\publish\CursorType.exe"
cd "%~dp0\Input and Commands\ProgrammaticFocusControl\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Input and Commands\ProgrammaticFocusControl\bin\Debug\net5.0-windows\%1\publish\ProgrammaticFocusControl.exe"
cd "%~dp0\PerMonitorDPI\FormattedTextExample\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\PerMonitorDPI\FormattedTextExample\bin\Debug\net5.0-windows\%1\publish\FormattedTextExample.exe"
cd "%~dp0\PerMonitorDPI\ImageScaling\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\PerMonitorDPI\ImageScaling\bin\Debug\net5.0-windows\%1\publish\ImageScaling.exe"
cd "%~dp0\PerMonitorDPI\TextFormatting\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\PerMonitorDPI\TextFormatting\bin\Debug\net5.0-windows\%1\publish\TextFormatting.exe"
cd "%~dp0\Properties\Callbacks\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Properties\Callbacks\bin\Debug\net5.0-windows\%1\publish\Callbacks.exe"
cd "%~dp0\Properties\CustomClassesWithDP\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Properties\CustomClassesWithDP\bin\Debug\net5.0-windows\%1\publish\CustomClassesWithDP.exe"
cd "%~dp0\Properties\RestoringDefaultValues\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Properties\RestoringDefaultValues\bin\Debug\net5.0-windows\%1\publish\RestoringDefaultValues.exe"
cd "%~dp0\Resources\ApplicationResources\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Resources\ApplicationResources\bin\Debug\net5.0-windows\%1\publish\ApplicationResources.exe"
cd "%~dp0\Resources\DefiningResources\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Resources\DefiningResources\bin\Debug\net5.0-windows\%1\publish\DefiningResources.exe"
cd "%~dp0\Resources\MergedResources\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Resources\MergedResources\bin\Debug\net5.0-windows\%1\publish\MergedResources.exe"
cd "%~dp0\Sample Applications\CalculatorDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\CalculatorDemo\bin\Debug\net5.0-windows\%1\publish\CalculatorDemo.exe"
cd "%~dp0\Sample Applications\ConcentricRingsDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\ConcentricRingsDemo\bin\Debug\net5.0-windows\%1\publish\ConcentricRingsDemo.exe"
cd "%~dp0\Sample Applications\CubeAnimationDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\CubeAnimationDemo\bin\Debug\net5.0-windows\%1\publish\CubeAnimationDemo.exe"
cd "%~dp0\Sample Applications\CustomComboBox\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\CustomComboBox\bin\Debug\net5.0-windows\%1\publish\CustomComboBox.exe"
cd "%~dp0\Sample Applications\DataBindingDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\DataBindingDemo\bin\Debug\net5.0-windows\%1\publish\DataBindingDemo.exe"
cd "%~dp0\Sample Applications\DropShadow\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\DropShadow\bin\Debug\net5.0-windows\%1\publish\DropShadow.exe"
cd "%~dp0\Sample Applications\EditingExaminerDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\EditingExaminerDemo\bin\Debug\net5.0-windows\%1\publish\EditingExaminerDemo.exe"
cd "%~dp0\Sample Applications\ExpenseIt\ExpenseItDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\ExpenseIt\ExpenseItDemo\bin\Debug\net5.0-windows\%1\publish\ExpenseIt9.exe"
cd "%~dp0\Sample Applications\FontDialog\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\FontDialog\bin\Debug\net5.0-windows\%1\publish\FontDialog.exe"
cd "%~dp0\Sample Applications\GeometryDesignerDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\GeometryDesignerDemo\bin\Debug\net5.0-windows\%1\publish\GeometryDesignerDemo.exe"
cd "%~dp0\Sample Applications\GraphingCalculatorDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\GraphingCalculatorDemo\bin\Debug\net5.0-windows\%1\publish\GraphingCalculatorDemo.exe"
cd "%~dp0\Sample Applications\HexSphereDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\HexSphereDemo\bin\Debug\net5.0-windows\%1\publish\HexSphereDemo.exe"
cd "%~dp0\Sample Applications\HtmlToXamlDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\HtmlToXamlDemo\bin\Debug\net5.0-windows\%1\publish\HtmlToXamlDemo.exe"
cd "%~dp0\Sample Applications\LayoutTransitionsDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\LayoutTransitionsDemo\bin\Debug\net5.0-windows\%1\publish\LayoutTransitionsDemo.exe"
cd "%~dp0\Sample Applications\ParticlesDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\ParticlesDemo\bin\Debug\net5.0-windows\%1\publish\ParticlesDemo.exe"
cd "%~dp0\Sample Applications\PhotoFlipperDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\PhotoFlipperDemo\bin\Debug\net5.0-windows\%1\publish\PhotoFlipperDemo.exe"
cd "%~dp0\Sample Applications\PhotoStoreDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\PhotoStoreDemo\bin\Debug\net5.0-windows\%1\publish\PhotoStoreDemo.exe"
cd "%~dp0\Sample Applications\PhotoViewerDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\PhotoViewerDemo\bin\Debug\net5.0-windows\%1\publish\PhotoViewerDemo.exe"
cd "%~dp0\Sample Applications\SlidePuzzleDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\SlidePuzzleDemo\bin\Debug\net5.0-windows\%1\publish\SlidePuzzleDemo.exe"
cd "%~dp0\Sample Applications\StickyNotesDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\StickyNotesDemo\bin\Debug\net5.0-windows\%1\publish\StickyNotesDemo.exe"
cd "%~dp0\Sample Applications\VideoViewerDemo\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Sample Applications\VideoViewerDemo\bin\Debug\net5.0-windows\%1\publish\VideoViewerDemo.exe"
cd "%~dp0\Speech and Media\MediaGallery\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Speech and Media\MediaGallery\bin\Debug\net5.0-windows\%1\publish\MediaGallery.exe"
cd "%~dp0\Styles & Templates\AlternatingAppearanceOfItems\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Styles & Templates\AlternatingAppearanceOfItems\bin\Debug\net5.0-windows\%1\publish\AlternatingAppearanceOfItems.exe"
cd "%~dp0\Styles & Templates\ContentControlStyle\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Styles & Templates\ContentControlStyle\bin\Debug\net5.0-windows\%1\publish\ContentControlStyle.exe"
cd "%~dp0\Styles & Templates\EventTriggers\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Styles & Templates\EventTriggers\bin\Debug\net5.0-windows\%1\publish\EventTriggers.exe"
cd "%~dp0\Styles & Templates\FindingElementsInTemplates\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Styles & Templates\FindingElementsInTemplates\bin\Debug\net5.0-windows\%1\publish\FindingElementsInTemplates.exe"
cd "%~dp0\Styles & Templates\IntroToStylingAndTemplating\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Styles & Templates\IntroToStylingAndTemplating\bin\Debug\net5.0-windows\%1\publish\IntroToStylingAndTemplating.exe"
cd "%~dp0\Threading\MultiThreadingWebBrowser\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Threading\MultiThreadingWebBrowser\bin\Debug\net5.0-windows\%1\publish\MultiThreadingWebBrowser.exe"
cd "%~dp0\Threading\SingleThreadedApplication\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Threading\SingleThreadedApplication\bin\Debug\net5.0-windows\%1\publish\SingleThreadedApplication.exe"
cd "%~dp0\Threading\UsingDispatcher\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Threading\UsingDispatcher\bin\Debug\net5.0-windows\%1\publish\UsingDispatcher.exe"
cd "%~dp0\Visual Layer\CompositionTarget\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Visual Layer\CompositionTarget\bin\Debug\net5.0-windows\%1\publish\CompositionTarget.exe"
cd "%~dp0\Visual Layer\DrawingVisual\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Visual Layer\DrawingVisual\bin\Debug\net5.0-windows\%1\publish\DrawingVisual.exe"
cd "%~dp0\Visual Layer\VisualsHitTesting\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Visual Layer\VisualsHitTesting\bin\Debug\net5.0-windows\%1\publish\VisualsHitTesting.exe"
cd "%~dp0\Windows\CustomWindowUI\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\CustomWindowUI\bin\Debug\net5.0-windows\%1\publish\CustomWindowUI.exe"
cd "%~dp0\Windows\DialogBox\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\DialogBox\bin\Debug\net5.0-windows\%1\publish\DialogBox.exe"
cd "%~dp0\Windows\MessageBox\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\MessageBox\bin\Debug\net5.0-windows\%1\publish\MessageBox.exe"
cd "%~dp0\Windows\NonRectangularWindow\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\NonRectangularWindow\bin\Debug\net5.0-windows\%1\publish\NonRectangularWindow.exe"
cd "%~dp0\Windows\NotificationIcon\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\NotificationIcon\bin\Debug\net5.0-windows\%1\publish\NotificationIcon.exe"
cd "%~dp0\Windows\SaveWindowState\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\SaveWindowState\bin\Debug\net5.0-windows\%1\publish\SaveWindowState.exe"
cd "%~dp0\Windows\ShowWindowWithoutActivation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\ShowWindowWithoutActivation\bin\Debug\net5.0-windows\%1\publish\ShowWindowWithoutActivation.exe"
cd "%~dp0\Windows\WindowActivationAndDeactivation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\WindowActivationAndDeactivation\bin\Debug\net5.0-windows\%1\publish\WindowActivationAndDeactivation.exe"
cd "%~dp0\Windows\WindowHiding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\WindowHiding\bin\Debug\net5.0-windows\%1\publish\WindowHiding.exe"
cd "%~dp0\Windows\WindowSizingOrder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\WindowSizingOrder\bin\Debug\net5.0-windows\%1\publish\WindowSizingOrder.exe"
cd "%~dp0\Windows\Wizard\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Windows\Wizard\bin\Debug\net5.0-windows\%1\publish\Wizard.exe"

