REM runsamples_block1.bat <runtime identifier>
REM ex: runsamples_block1 win-x64
REM ex: runsamples_block1 win-arm64
REM ex: runsamples_block1 win-x86
cd "%~dp0\Accessibility\FetchTimer\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\FetchTimer\bin\Debug\net5.0-windows\%1\publish\FetchTimer.exe"
cd "%~dp0\Accessibility\FindText\FindText\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\FindText\FindText\bin\Debug\net5.0-windows\%1\publish\FindText.exe"
cd "%~dp0\Accessibility\FocusTracker\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\FocusTracker\bin\Debug\net5.0-windows\%1\publish\FocusTracker.exe"
cd "%~dp0\Accessibility\InsertText\InsertTextTarget\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\InsertText\InsertTextTarget\bin\Debug\net5.0-windows\%1\publish\InsertTextTarget.exe"
cd "%~dp0\Accessibility\InvokePattern\Target\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\InvokePattern\Target\bin\Debug\net5.0-windows\%1\publish\Target.exe"
cd "%~dp0\Accessibility\SelectionPattern\SelectionTarget\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\SelectionPattern\SelectionTarget\bin\Debug\net5.0-windows\%1\publish\SelectionTarget.exe"
cd "%~dp0\Accessibility\WindowMove\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Accessibility\WindowMove\bin\Debug\net5.0-windows\%1\publish\WindowMove.exe"
cd "%~dp0\Animation\AnimationExamples\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\AnimationExamples\bin\Debug\net5.0-windows\%1\publish\AnimationExamples.exe"
cd "%~dp0\Animation\AnimationTiming\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\AnimationTiming\bin\Debug\net5.0-windows\%1\publish\AnimationTiming.exe"
cd "%~dp0\Animation\CustomAnimation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\CustomAnimation\bin\Debug\net5.0-windows\%1\publish\CustomAnimation.exe"
cd "%~dp0\Animation\KeyFrameAnimation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\KeyFrameAnimation\bin\Debug\net5.0-windows\%1\publish\KeyFrameAnimation.exe"
cd "%~dp0\Animation\KeySplineAnimations\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\KeySplineAnimations\bin\Debug\net5.0-windows\%1\publish\KeySplineAnimations.exe"
cd "%~dp0\Animation\LocalAnimations\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\LocalAnimations\bin\Debug\net5.0-windows\%1\publish\LocalAnimations.exe"
cd "%~dp0\Animation\OpacityAnimation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\OpacityAnimation\bin\Debug\net5.0-windows\%1\publish\OpacityAnimation.exe"
cd "%~dp0\Animation\PathAnimations\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\PathAnimations\bin\Debug\net5.0-windows\%1\publish\PathAnimations.exe"
cd "%~dp0\Animation\Per-FrameAnimation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\Per-FrameAnimation\bin\Debug\net5.0-windows\%1\publish\Per-FrameAnimation.exe"
cd "%~dp0\Animation\PropertyAnimation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\PropertyAnimation\bin\Debug\net5.0-windows\%1\publish\PropertyAnimation.exe"
cd "%~dp0\Animation\TargetValues\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Animation\TargetValues\bin\Debug\net5.0-windows\%1\publish\TargetValues.exe"
cd "%~dp0\Application Management\ApplicationShutdown\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\ApplicationShutdown\bin\Debug\net5.0-windows\%1\publish\ApplicationShutdown.exe"
cd "%~dp0\Application Management\CodeOnlyWindowsApplication\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\CodeOnlyWindowsApplication\bin\Debug\net5.0-windows\%1\publish\CodeOnlyWindowsApplication.exe"
cd "%~dp0\Application Management\CustomApplication\CustomApplicationClass\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\CustomApplication\CustomApplicationClass\bin\Debug\net5.0-windows\%1\publish\CustomApplicationClass.exe"
cd "%~dp0\Application Management\ExceptionHandlingSecondaryUIThread\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\ExceptionHandlingSecondaryUIThread\bin\Debug\net5.0-windows\%1\publish\ExceptionHandlingSecondaryUIThread.exe"
cd "%~dp0\Application Management\ExceptionHandlingSecondaryWorkerThread\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\ExceptionHandlingSecondaryWorkerThread\bin\Debug\net5.0-windows\%1\publish\ExceptionHandlingSecondaryWorkerThread.exe"
cd "%~dp0\Application Management\ProcessingCommandLineArguments\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\ProcessingCommandLineArguments\bin\Debug\net5.0-windows\%1\publish\ProcessingCommandLineArguments.exe"
cd "%~dp0\Application Management\SkinnedApplication\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\SkinnedApplication\bin\Debug\net5.0-windows\%1\publish\SkinnedApplication.exe"
cd "%~dp0\Application Management\UnhandledExceptionHandling\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Application Management\UnhandledExceptionHandling\bin\Debug\net5.0-windows\%1\publish\UnhandledExceptionHandling.exe"
cd "%~dp0\Clipboard\ClipboardSpy\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Clipboard\ClipboardSpy\bin\Debug\net5.0-windows\%1\publish\ClipboardSpy.exe"
cd "%~dp0\Clipboard\ClipboardViewer\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Clipboard\ClipboardViewer\bin\Debug\net5.0-windows\%1\publish\ClipboardViewer.exe"
cd "%~dp0\Compatibility\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Compatibility\bin\Debug\net5.0-windows\%1\publish\AppCompat-Quirks.exe"
cd "%~dp0\Data Binding\BindConversion\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\BindConversion\bin\Debug\net5.0-windows\%1\publish\BindConversion.exe"
cd "%~dp0\Data Binding\BindingDPToDP\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\BindingDPToDP\bin\Debug\net5.0-windows\%1\publish\BindingDPToDP.exe"
cd "%~dp0\Data Binding\BindingToMethod\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\BindingToMethod\bin\Debug\net5.0-windows\%1\publish\BindingToMethod.exe"
cd "%~dp0\Data Binding\BindValidation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\BindValidation\bin\Debug\net5.0-windows\%1\publish\BindValidation.exe"
cd "%~dp0\Data Binding\BusinessLayerValidation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\BusinessLayerValidation\bin\Debug\net5.0-windows\%1\publish\BusinessLayerValidation.exe"
cd "%~dp0\Data Binding\CodeOnlyBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\CodeOnlyBinding\bin\Debug\net5.0-windows\%1\publish\CodeOnlyBinding.exe"
cd "%~dp0\Data Binding\CollectionBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\CollectionBinding\bin\Debug\net5.0-windows\%1\publish\CollectionBinding.exe"
cd "%~dp0\Data Binding\CollectionViewSource\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\CollectionViewSource\bin\Debug\net5.0-windows\%1\publish\CollectionViewSource.exe"
cd "%~dp0\Data Binding\Colors\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\Colors\bin\Debug\net5.0-windows\%1\publish\Colors.exe"
cd "%~dp0\Data Binding\CompositeCollections\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\CompositeCollections\bin\Debug\net5.0-windows\%1\publish\CompositeCollections.exe"
cd "%~dp0\Data Binding\DataBindingToStringFomat\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\DataBindingToStringFomat\bin\Debug\net5.0-windows\%1\publish\DataBindingToStringFomat.exe"
cd "%~dp0\Data Binding\DataTemplatingIntro\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\DataTemplatingIntro\bin\Debug\net5.0-windows\%1\publish\DataTemplatingIntro.exe"
cd "%~dp0\Data Binding\DataTrigger\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\DataTrigger\bin\Debug\net5.0-windows\%1\publish\DataTrigger.exe"
cd "%~dp0\Data Binding\DirectionalBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\DirectionalBinding\bin\Debug\net5.0-windows\%1\publish\DirectionalBinding.exe"
cd "%~dp0\Data Binding\EditingCollections\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\EditingCollections\bin\Debug\net5.0-windows\%1\publish\EditingCollections.exe"
cd "%~dp0\Data Binding\Grouping\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\Grouping\bin\Debug\net5.0-windows\%1\publish\Grouping.exe"
cd "%~dp0\Data Binding\HierarchicalDataTemplate\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\HierarchicalDataTemplate\bin\Debug\net5.0-windows\%1\publish\HierarchicalDataTemplate.exe"
cd "%~dp0\Data Binding\Linq\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\Linq\bin\Debug\net5.0-windows\%1\publish\Linq.exe"
cd "%~dp0\Data Binding\MasterDetail\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\MasterDetail\bin\Debug\net5.0-windows\%1\publish\MasterDetail.exe"
cd "%~dp0\Data Binding\MasterDetailXml\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\MasterDetailXml\bin\Debug\net5.0-windows\%1\publish\MasterDetailXml.exe"
cd "%~dp0\Data Binding\MultiBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\MultiBinding\bin\Debug\net5.0-windows\%1\publish\MultiBinding.exe"
cd "%~dp0\Data Binding\PriorityBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\PriorityBinding\bin\Debug\net5.0-windows\%1\publish\PriorityBinding.exe"
cd "%~dp0\Data Binding\PropertyChangeNotification\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\PropertyChangeNotification\bin\Debug\net5.0-windows\%1\publish\PropertyChangeNotification.exe"
cd "%~dp0\Data Binding\SimpleBinding\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\SimpleBinding\bin\Debug\net5.0-windows\%1\publish\SimpleBinding.exe"
cd "%~dp0\Data Binding\SortFilter\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\SortFilter\bin\Debug\net5.0-windows\%1\publish\SortFilter.exe"
cd "%~dp0\Data Binding\UpdateSource\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\UpdateSource\bin\Debug\net5.0-windows\%1\publish\UpdateSource.exe"
cd "%~dp0\Data Binding\ValidateItemSample\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\ValidateItemSample\bin\Debug\net5.0-windows\%1\publish\ValidateItemSample.exe"
cd "%~dp0\Data Binding\ValidateItemsInItemsControl\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\ValidateItemsInItemsControl\bin\Debug\net5.0-windows\%1\publish\ValidateItemsInItemsControl.exe"
cd "%~dp0\Data Binding\XmlDataSource\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\XmlDataSource\bin\Debug\net5.0-windows\%1\publish\XmlDataSource.exe"
cd "%~dp0\Data Binding\XmlnsBind\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Data Binding\XmlnsBind\bin\Debug\net5.0-windows\%1\publish\XmlnsBind.exe"
cd "%~dp0\Documents\Annotations\AnnotatedDocumentViewer\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Annotations\AnnotatedDocumentViewer\bin\Debug\net5.0-windows\%1\publish\AnnotatedDocumentViewer.exe"
cd "%~dp0\Documents\Annotations\AnnotationsStyling\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Annotations\AnnotationsStyling\bin\Debug\net5.0-windows\%1\publish\AnnotationsStyling.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentMerge\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Fixed Documents\DocumentMerge\bin\Debug\net5.0-windows\%1\publish\DocumentMerge.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentSerialization\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Fixed Documents\DocumentSerialization\bin\Debug\net5.0-windows\%1\publish\DocumentSerialization.exe"
cd "%~dp0\Documents\Fixed Documents\DocumentStructure\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Fixed Documents\DocumentStructure\bin\Debug\net5.0-windows\%1\publish\DocumentStructure.exe"
cd "%~dp0\Documents\Flow Content\FlowContentElements\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\FlowContentElements\bin\Debug\net5.0-windows\%1\publish\FlowContentElements.exe"
cd "%~dp0\Documents\Flow Content\FlowContentProperty\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\FlowContentProperty\bin\Debug\net5.0-windows\%1\publish\FlowContentProperty.exe"
cd "%~dp0\Documents\Flow Content\FlowDocumentNewsClient\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\FlowDocumentNewsClient\bin\Debug\net5.0-windows\%1\publish\FlowDocumentNewsClient.exe"

