REM runsamples_block2.bat <runtime identifier>
REM ex: runsamples_block2 win-x64
REM ex: runsamples_block2 win-arm64
REM ex: runsamples_block2 win-x86
cd "%~dp0\Documents\Flow Content\FlowDocumentProperties\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\FlowDocumentProperties\bin\Debug\net5.0-windows\%1\publish\FlowDocumentProperties.exe"
cd "%~dp0\Documents\Flow Content\FontProperties\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\FontProperties\bin\Debug\net5.0-windows\%1\publish\FontProperties.exe"
cd "%~dp0\Documents\Flow Content\ParagraphAndHyphenation\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\ParagraphAndHyphenation\bin\Debug\net5.0-windows\%1\publish\ParagraphAndHyphenation.exe"
cd "%~dp0\Documents\Flow Content\TableBuilder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\TableBuilder\bin\Debug\net5.0-windows\%1\publish\TableBuilder.exe"
cd "%~dp0\Documents\Flow Content\TableRows\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\TableRows\bin\Debug\net5.0-windows\%1\publish\TableRows.exe"
cd "%~dp0\Documents\Flow Content\TabularData\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\TabularData\bin\Debug\net5.0-windows\%1\publish\TabularData.exe"
cd "%~dp0\Documents\Flow Content\TextWrapProperty\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Flow Content\TextWrapProperty\bin\Debug\net5.0-windows\%1\publish\TextWrapProperty.exe"
cd "%~dp0\Documents\Spell Checking\CustomDictionaries\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Spell Checking\CustomDictionaries\bin\Debug\net5.0-windows\%1\publish\CustomDictionaries.exe"
cd "%~dp0\Documents\Spell Checking\SpellChecking\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Documents\Spell Checking\SpellChecking\bin\Debug\net5.0-windows\%1\publish\SpellChecking.exe"
cd "%~dp0\Drag and Drop\DragDropDataFormats\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropDataFormats\bin\Debug\net5.0-windows\%1\publish\DragDropDataFormats.exe"
cd "%~dp0\Drag and Drop\DragDropEvents\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropEvents\bin\Debug\net5.0-windows\%1\publish\DragDropEvents.exe"
cd "%~dp0\Drag and Drop\DragDropObjects\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropObjects\bin\Debug\net5.0-windows\%1\publish\DragDropObjects.exe"
cd "%~dp0\Drag and Drop\DragDropOpenTextFile\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropOpenTextFile\bin\Debug\net5.0-windows\%1\publish\DragDropOpenTextFile.exe"
cd "%~dp0\Drag and Drop\DragDropTextOps\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropTextOps\bin\Debug\net5.0-windows\%1\publish\DragDropTextOps.exe"
cd "%~dp0\Drag and Drop\DragDropThumbOps\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Drag and Drop\DragDropThumbOps\bin\Debug\net5.0-windows\%1\publish\DragDropThumbOps.exe"
cd "%~dp0\Element Tree\OverridingLogicalTree\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Element Tree\OverridingLogicalTree\bin\Debug\net5.0-windows\%1\publish\OverridingLogicalTree.exe"
cd "%~dp0\Element Tree\SearchingForElement\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Element Tree\SearchingForElement\bin\Debug\net5.0-windows\%1\publish\SearchingForElement.exe"
cd "%~dp0\Elements\ContextMenuOpening\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\ContextMenuOpening\bin\Debug\net5.0-windows\%1\publish\ContextMenuOpening.exe"
cd "%~dp0\Elements\FindingElementInPanel\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\FindingElementInPanel\bin\Debug\net5.0-windows\%1\publish\FindingElementInPanel.exe"
cd "%~dp0\Elements\FocusVisualStyle\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\FocusVisualStyle\bin\Debug\net5.0-windows\%1\publish\FocusVisualStyle.exe"
cd "%~dp0\Elements\HeightProperties\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\HeightProperties\bin\Debug\net5.0-windows\%1\publish\HeightProperties.exe"
cd "%~dp0\Elements\LoadedEvent\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\LoadedEvent\bin\Debug\net5.0-windows\%1\publish\LoadedEvent.exe"
cd "%~dp0\Elements\SettingMargins\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\SettingMargins\bin\Debug\net5.0-windows\%1\publish\SettingMargins.exe"
cd "%~dp0\Elements\ThicknessConverter\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\ThicknessConverter\bin\Debug\net5.0-windows\%1\publish\ThicknessConverter.exe"
cd "%~dp0\Elements\UsingElements\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\UsingElements\bin\Debug\net5.0-windows\%1\publish\UsingElements.exe"
cd "%~dp0\Elements\VisibiltyChanges\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\VisibiltyChanges\bin\Debug\net5.0-windows\%1\publish\VisibiltyChanges.exe"
cd "%~dp0\Elements\WidthProperties\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Elements\WidthProperties\bin\Debug\net5.0-windows\%1\publish\WidthProperties.exe"
cd "%~dp0\Events\AddingEventHandler\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Events\AddingEventHandler\bin\Debug\net5.0-windows\%1\publish\AddingEventHandler.exe"
cd "%~dp0\Events\CustomRoutedEvents\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Events\CustomRoutedEvents\bin\Debug\net5.0-windows\%1\publish\CustomRoutedEvents.exe"
cd "%~dp0\Events\FindingSourceElement\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Events\FindingSourceElement\bin\Debug\net5.0-windows\%1\publish\FindingSourceElement.exe"
cd "%~dp0\Events\RoutedEventHandling\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Events\RoutedEventHandling\bin\Debug\net5.0-windows\%1\publish\RoutedEventHandling.exe"
cd "%~dp0\Getting Started\ComplexLayout\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\ComplexLayout\bin\Debug\net5.0-windows\%1\publish\ComplexLayout.exe"
cd "%~dp0\Getting Started\Concepts\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\Concepts\bin\Debug\net5.0-windows\%1\publish\Concepts.exe"
cd "%~dp0\Getting Started\ControlsAndLayout\ControlsAndLayout\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\ControlsAndLayout\ControlsAndLayout\bin\Debug\net5.0-windows\%1\publish\ControlsAndLayout.exe"
cd "%~dp0\Getting Started\DynamicLayout\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\DynamicLayout\bin\Debug\net5.0-windows\%1\publish\DynamicLayout.exe"
cd "%~dp0\Getting Started\HelloWorld\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\HelloWorld\bin\Debug\net5.0-windows\%1\publish\HelloWorld.exe"
cd "%~dp0\Getting Started\MultiPage\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\MultiPage\bin\Debug\net5.0-windows\%1\publish\MultiPage.exe"
cd "%~dp0\Getting Started\SimpleLayout\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\SimpleLayout\bin\Debug\net5.0-windows\%1\publish\SimpleLayout.exe"
cd "%~dp0\Getting Started\WalkthroughFirstWPFApp\csharp\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Getting Started\WalkthroughFirstWPFApp\csharp\bin\Debug\net5.0-windows\%1\publish\ExpenseIt9.exe"
cd "%~dp0\Globalization and Localization\BAML Loc\LocApp\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\BAML Loc\LocApp\bin\Debug\net5.0-windows\%1\publish\LocApp.exe"
cd "%~dp0\Globalization and Localization\FlowDirection\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\FlowDirection\bin\Debug\net5.0-windows\%1\publish\FlowDirection.exe"
cd "%~dp0\Globalization and Localization\GlobalizationHomepage\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\GlobalizationHomepage\bin\Debug\net5.0-windows\%1\publish\GlobalizationHomepage.exe"
cd "%~dp0\Globalization and Localization\GlobalizationRunDialog\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\GlobalizationRunDialog\bin\Debug\net5.0-windows\%1\publish\GlobalizationRunDialog.exe"
cd "%~dp0\Globalization and Localization\Gradient\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\Gradient\bin\Debug\net5.0-windows\%1\publish\Gradient.exe"
cd "%~dp0\Globalization and Localization\Image\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\Image\bin\Debug\net5.0-windows\%1\publish\Image.exe"
cd "%~dp0\Globalization and Localization\LangAttribute\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\LangAttribute\bin\Debug\net5.0-windows\%1\publish\LangAttribute.exe"
cd "%~dp0\Globalization and Localization\LocalizationResources\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\LocalizationResources\bin\Debug\net5.0-windows\%1\publish\LocalizationResources.exe"
cd "%~dp0\Globalization and Localization\LTRRTL\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\LTRRTL\bin\Debug\net5.0-windows\%1\publish\LTRRTL.exe"
cd "%~dp0\Globalization and Localization\NumbersMultipleLangauges\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\NumbersMultipleLangauges\bin\Debug\net5.0-windows\%1\publish\NumbersMultipleLangauges.exe"
cd "%~dp0\Globalization and Localization\Paths\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\Paths\bin\Debug\net5.0-windows\%1\publish\Paths.exe"
cd "%~dp0\Globalization and Localization\RunSpan\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\RunSpan\bin\Debug\net5.0-windows\%1\publish\RunSpan.exe"
cd "%~dp0\Globalization and Localization\Span\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\Span\bin\Debug\net5.0-windows\%1\publish\Span.exe"
cd "%~dp0\Globalization and Localization\StringLocalizationSample\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Globalization and Localization\StringLocalizationSample\bin\Debug\net5.0-windows\%1\publish\StringLocalizationSample.exe"
cd "%~dp0\Graphics\2DTransforms\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\2DTransforms\bin\Debug\net5.0-windows\%1\publish\2DTransforms.exe"
cd "%~dp0\Graphics\BitmapEffectsGallery\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\BitmapEffectsGallery\bin\Debug\net5.0-windows\%1\publish\BitmapEffectsGallery.exe"
cd "%~dp0\Graphics\BitmapMetadata\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\BitmapMetadata\bin\Debug\net5.0-windows\%1\publish\BitmapMetadata.exe"
cd "%~dp0\Graphics\BMPEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\BMPEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\BMPEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Brushes\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Brushes\bin\Debug\net5.0-windows\%1\publish\Brushes.exe"
cd "%~dp0\Graphics\ClipRegion\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\ClipRegion\bin\Debug\net5.0-windows\%1\publish\ClipRegion.exe"
cd "%~dp0\Graphics\Converter\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Converter\bin\Debug\net5.0-windows\%1\publish\Converter.exe"
cd "%~dp0\Graphics\DrawingBrush\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\DrawingBrush\bin\Debug\net5.0-windows\%1\publish\DrawingBrush.exe"
cd "%~dp0\Graphics\Geometry\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Geometry\bin\Debug\net5.0-windows\%1\publish\Geometry.exe"
cd "%~dp0\Graphics\GIFEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\GIFEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\GIFEncoderAndDecoder.exe"
cd "%~dp0\Graphics\ImageBrush\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\ImageBrush\bin\Debug\net5.0-windows\%1\publish\ImageBrush.exe"
cd "%~dp0\Graphics\ImageView\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\ImageView\bin\Debug\net5.0-windows\%1\publish\ImageView.exe"
cd "%~dp0\Graphics\JPEGEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\JPEGEncoderAndDecoder\bin\Debug\net5.0-windows\%1\publish\JPEGEncoderAndDecoder.exe"
cd "%~dp0\Graphics\Matrix\bin\Debug\net5.0-windows\%1\publish\"
"%~dp0\Graphics\Matrix\bin\Debug\net5.0-windows\%1\publish\Matrix.exe"

