//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontDialog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontDialog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All petite caps.
        /// </summary>
        internal static string AllPetiteCaps {
            get {
                return ResourceManager.GetString("AllPetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All small caps.
        /// </summary>
        internal static string AllSmallCaps {
            get {
                return ResourceManager.GetString("AllSmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation alternates.
        /// </summary>
        internal static string AnnotationAlternates {
            get {
                return ResourceManager.GetString("AnnotationAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitals.
        /// </summary>
        internal static string Capitals {
            get {
                return ResourceManager.GetString("Capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital spacing.
        /// </summary>
        internal static string CapitalSpacing {
            get {
                return ResourceManager.GetString("CapitalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive forms.
        /// </summary>
        internal static string CaseSensitiveForms {
            get {
                return ResourceManager.GetString("CaseSensitiveForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contextual alternates.
        /// </summary>
        internal static string ContextualAlternates {
            get {
                return ResourceManager.GetString("ContextualAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligatures, contextual.
        /// </summary>
        internal static string ContextualLigatures {
            get {
                return ResourceManager.GetString("ContextualLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swashes, contextual.
        /// </summary>
        internal static string ContextualSwashes {
            get {
                return ResourceManager.GetString("ContextualSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, 2, 3, 4, 5, 6, 7, 8 ,9, 0.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligatures, discretionary.
        /// </summary>
        internal static string DiscretionaryLigatures {
            get {
                return ResourceManager.GetString("DiscretionaryLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Asian expert forms.
        /// </summary>
        internal static string EastAsianExpertForms {
            get {
                return ResourceManager.GetString("EastAsianExpertForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Asian language.
        /// </summary>
        internal static string EastAsianLanguage {
            get {
                return ResourceManager.GetString("EastAsianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Asian widths.
        /// </summary>
        internal static string EastAsianWidths {
            get {
                return ResourceManager.GetString("EastAsianWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction.
        /// </summary>
        internal static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical forms.
        /// </summary>
        internal static string HistoricalForms {
            get {
                return ResourceManager.GetString("HistoricalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligatures, historical.
        /// </summary>
        internal static string HistoricalLigatures {
            get {
                return ResourceManager.GetString("HistoricalLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hojo Kanji.
        /// </summary>
        internal static string HojoKanji {
            get {
                return ResourceManager.GetString("HojoKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior.
        /// </summary>
        internal static string Inferior {
            get {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIS-04.
        /// </summary>
        internal static string Jis04 {
            get {
                return ResourceManager.GetString("Jis04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIS-78.
        /// </summary>
        internal static string Jis78 {
            get {
                return ResourceManager.GetString("Jis78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIS-83.
        /// </summary>
        internal static string Jis83 {
            get {
                return ResourceManager.GetString("Jis83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIS-90.
        /// </summary>
        internal static string Jis90 {
            get {
                return ResourceManager.GetString("Jis90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerning.
        /// </summary>
        internal static string Kerning {
            get {
                return ResourceManager.GetString("Kerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lining.
        /// </summary>
        internal static string Lining {
            get {
                return ResourceManager.GetString("Lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical Greek.
        /// </summary>
        internal static string MathematicalGreek {
            get {
                return ResourceManager.GetString("MathematicalGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLC Kanji.
        /// </summary>
        internal static string NlcKanji {
            get {
                return ResourceManager.GetString("NlcKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeral alignment.
        /// </summary>
        internal static string NumeralAlignment {
            get {
                return ResourceManager.GetString("NumeralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeral style.
        /// </summary>
        internal static string NumeralStyle {
            get {
                return ResourceManager.GetString("NumeralStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old style.
        /// </summary>
        internal static string OldStyle {
            get {
                return ResourceManager.GetString("OldStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string OneHalf {
            get {
                return ResourceManager.GetString("OneHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petite caps.
        /// </summary>
        internal static string PetiteCaps {
            get {
                return ResourceManager.GetString("PetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional.
        /// </summary>
        internal static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby.
        /// </summary>
        internal static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified.
        /// </summary>
        internal static string Simplified {
            get {
                return ResourceManager.GetString("Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (simulated).
        /// </summary>
        internal static string simulated {
            get {
                return ResourceManager.GetString("simulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slashed.
        /// </summary>
        internal static string Slashed {
            get {
                return ResourceManager.GetString("Slashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slashed zero.
        /// </summary>
        internal static string SlashedZero {
            get {
                return ResourceManager.GetString("SlashedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small caps.
        /// </summary>
        internal static string SmallCaps {
            get {
                return ResourceManager.GetString("SmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked.
        /// </summary>
        internal static string Stacked {
            get {
                return ResourceManager.GetString("Stacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligatures, standard.
        /// </summary>
        internal static string StandardLigatures {
            get {
                return ResourceManager.GetString("StandardLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swashes, standard.
        /// </summary>
        internal static string StandardSwashes {
            get {
                return ResourceManager.GetString("StandardSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic alternates.
        /// </summary>
        internal static string StylisticAlternates {
            get {
                return ResourceManager.GetString("StylisticAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  1.
        /// </summary>
        internal static string StylisticSet1 {
            get {
                return ResourceManager.GetString("StylisticSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 10.
        /// </summary>
        internal static string StylisticSet10 {
            get {
                return ResourceManager.GetString("StylisticSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 11.
        /// </summary>
        internal static string StylisticSet11 {
            get {
                return ResourceManager.GetString("StylisticSet11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 12.
        /// </summary>
        internal static string StylisticSet12 {
            get {
                return ResourceManager.GetString("StylisticSet12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 13.
        /// </summary>
        internal static string StylisticSet13 {
            get {
                return ResourceManager.GetString("StylisticSet13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 14.
        /// </summary>
        internal static string StylisticSet14 {
            get {
                return ResourceManager.GetString("StylisticSet14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 15.
        /// </summary>
        internal static string StylisticSet15 {
            get {
                return ResourceManager.GetString("StylisticSet15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 16.
        /// </summary>
        internal static string StylisticSet16 {
            get {
                return ResourceManager.GetString("StylisticSet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 17.
        /// </summary>
        internal static string StylisticSet17 {
            get {
                return ResourceManager.GetString("StylisticSet17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 18.
        /// </summary>
        internal static string StylisticSet18 {
            get {
                return ResourceManager.GetString("StylisticSet18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 19.
        /// </summary>
        internal static string StylisticSet19 {
            get {
                return ResourceManager.GetString("StylisticSet19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  2.
        /// </summary>
        internal static string StylisticSet2 {
            get {
                return ResourceManager.GetString("StylisticSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set 20.
        /// </summary>
        internal static string StylisticSet20 {
            get {
                return ResourceManager.GetString("StylisticSet20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  3.
        /// </summary>
        internal static string StylisticSet3 {
            get {
                return ResourceManager.GetString("StylisticSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  4.
        /// </summary>
        internal static string StylisticSet4 {
            get {
                return ResourceManager.GetString("StylisticSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  5.
        /// </summary>
        internal static string StylisticSet5 {
            get {
                return ResourceManager.GetString("StylisticSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  6.
        /// </summary>
        internal static string StylisticSet6 {
            get {
                return ResourceManager.GetString("StylisticSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  7.
        /// </summary>
        internal static string StylisticSet7 {
            get {
                return ResourceManager.GetString("StylisticSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  8.
        /// </summary>
        internal static string StylisticSet8 {
            get {
                return ResourceManager.GetString("StylisticSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylistic set  9.
        /// </summary>
        internal static string StylisticSet9 {
            get {
                return ResourceManager.GetString("StylisticSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabular.
        /// </summary>
        internal static string Tabular {
            get {
                return ResourceManager.GetString("Tabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titling.
        /// </summary>
        internal static string Titling {
            get {
                return ResourceManager.GetString("Titling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        internal static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional names.
        /// </summary>
        internal static string TraditionalNames {
            get {
                return ResourceManager.GetString("TraditionalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicase.
        /// </summary>
        internal static string Unicase {
            get {
                return ResourceManager.GetString("Unicase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        internal static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
    }
}
